---
- hosts: app
  sudo: true
  vars:
    hostname: server-production
    environtment: production
    ruby_version: 2.2.0
    rbenv_root: /home/ec2-user/.rbenv
    rbenv_bin: /home/ec2-user/.rbenv/libexec/rbenv
  roles:
    - common
    - rvm
    - nginx
    - mysql
    - rails
    #- troubleshooting

