---
# rvm installation
- name: install rvm
  shell: sudo gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
- name: install rvm
  shell: curl -sSL https://rvm.io/mpapis.asc
- name: install rvm
  shell: creates=/etc/profile.d/rvm.sh curl -sSL https://get.rvm.io | bash -s stable --ruby={{ ruby_version }}
- name: remove rvm warning
  shell: export rvmsudo_secure_path=1
- name: set .gemrc
  shell: "echo 'gem: --no-rdoc --no-ri' > $HOME/.gemrc"

